### PR TITLE
Create Renovate bot configuration file

### LINKED ISSUE #43: Migrate from Dependabot to Renovatebot
I can help with migrating this repository to Renovate bot.

I think that would have the following benefits:

- Able to schedule updates when you like
- You can get a PR to update your lockfile weekly (or monthly or whatever schedule you like)
- Ability to automerge PRs if tests pass
- Includes a nice dashboard issue, that you can pin in your issue list, this shows you all pending updates
- You can configure the bot to only give you major type updates when you tick a checkbox in the Dependency Dashboard issue
- The ability to group certain dependencies together (like group `react-dom` and `react` into one)

Drawbacks of using Renovate bot:

- You need to install the Renovate bot app into your account whereas Dependabot is built in into GitHub
- If you have complicated requirements, it can be a bit of work to figure out how to configure the bot properly

I've made a carbon copy of the `octoclairvoyant` repository to test out a basic but nice Renovate bot configuration. If you want to see how that works, I can give you read access so that you can see how it works, and ask questions there. 😄

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes

- Create `renovate.json` file

## Context

Merge this PR once you see the Renovate bot onboarding PR on your repository. Renovate bot will then automatically close the onboarding PR (which you don't need now anyways, as you're using my config...).

Be sure to merge the "Pin dependencies" PR that Renovate bot will create, **before** you start merging **any** other PRs from Renovate bot. 😉 

Fixes #43.

### CODE REVIEW

**Comment by Belco90** [comment]
Sorry, but I'm not really sure what I need to do with Renovate bot before merging this?

**Comment by HonkingGoose** [comment]
> Sorry, but I'm not really sure what I need to do with Renovate bot before merging this?

1. First you need to install the Renovate bot app from the GitHub marketplace https://github.com/marketplace/renovate. For pictures of the installation process see the official Renovate docs: https://docs.renovatebot.com/install-github-app/
2. When installing the app, you can choose if you want Renovate bot to work on all repositories, or just on the ones you select.
3. Click the "Only select repositories" checkbox, and select your `octoclairvoyant` repository.
4. Renovate bot will then create a "Onboarding pull request" on the `octoclairvoyant` repository.

Once you see the "Onboarding pull request" from Renovate bot, ping me again, and I'll help you with the next steps.

**Comment by Belco90** [comment]
@HonkingGoose Ah yes, you already mentioned those steps. My bad, I understood I had to do something else.

**Comment by Belco90** [comment]
@HonkingGoose Alright! Renovate bot installed and Onboarding PR received! https://github.com/Belco90/octoclairvoyant/pull/67

**Comment by HonkingGoose** [comment]
@Belco90 Cool! Let's get you started with the next steps then. 😄 

Step 1: Merge the configuration PR you got from me (#65).

Step 2: Renovate bot will automatically close the Onboarding PR (#67), as it will see that the repo contains a `renovate.json` config file.

Step 3: After you've merged my configuration PR (#65), Renovate bot will start "running for real" and create update PRs for dependencies/actions.

Step 4: Review and merge the "Pin dependencies" PR from Renovate bot, before you start merging **any** other update PRs. The "Pin dependencies" PR will "pin" all versions in the `package.json` to a single version, instead of a range.
We'll update the lockfile weekly with the "Lockfile update PR" on Mondays.

**Review by Belco90 — APPROVED** [review]

**Comment by Belco90** [comment]
Cool! I've merged this PR, waiting for Renovate bot new PRs now.

**Pull request merged**
